export const ErrorCodes = {
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION__INVALID_INPUT',
    INVALID_EMAIL: 'VALIDATION__INVALID_EMAIL',
    PASSWORD_TOO_SHORT: 'VALIDATION__PASSWORD_TOO_SHORT',
    REQUIRED: 'VALIDATION__REQUIRED',
    FULLNAME_TOO_SHORT: 'VALIDATION__FULLNAME_TOO_SHORT'
  },
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH__INVALID_CREDENTIALS',
    ACCESS_DENIED: 'AUTH__ACCESS_DENIED',
    REFRESH_TOKEN_EXPIRED: 'AUTH__REFRESH_TOKEN_EXPIRED',
    EMAIL_ALREADY_EXISTS: 'AUTH__EMAIL_ALREADY_EXISTS',
  },
  CLASS: {
    NOT_FOUND: 'CLASS__NOT_FOUND',
    STUDENT_ALREADY_ENROLLED: 'CLASS__STUDENT_ALREADY_ENROLLED',
  },
  INVOICE: {
    DUPLICATE_PERIOD: 'INVOICE__DUPLICATE_PERIOD',
    STUDENT_NOT_ENROLLED: 'INVOICE__STUDENT_NOT_ENROLLED',
  },
  PAYMENT: {
    INVOICE_NOT_FOUND: 'PAYMENT__INVOICE_NOT_FOUND',
    INVOICE_ALREADY_PAID: 'PAYMENT__INVOICE_ALREADY_PAID',
  },
} as const;
