export const ErrorCodes = {
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH__INVALID_CREDENTIALS',
    ACCESS_DENIED: 'AUTH__ACCESS_DENIED',
    REFRESH_TOKEN_EXPIRED: 'AUTH__REFRESH_TOKEN_EXPIRED',
  },
  CLASS: {
    NOT_FOUND: 'CLASS__NOT_FOUND',
    STUDENT_ALREADY_ENROLLED: 'CLASS__STUDENT_ALREADY_ENROLLED',
  },
  INVOICE: {
    DUPLICATE_PERIOD: 'INVOICE__DUPLICATE_PERIOD',
    STUDENT_NOT_ENROLLED: 'INVOICE__STUDENT_NOT_ENROLLED',
  },
  PAYMENT: {
    INVOICE_NOT_FOUND: 'PAYMENT__INVOICE_NOT_FOUND',
    INVOICE_ALREADY_PAID: 'PAYMENT__INVOICE_ALREADY_PAID',
  },
} as const;
